#!/usr/bin/env bash

#set -ex

CURDIR=$(cd $(dirname $0) && pwd)
PKG_DIR_PATH=$(cd $CURDIR/../ && pwd)
package_name=$(basename $(realpath $PKG_DIR_PATH))
secret_file="${PKG_DIR_PATH}/.secrets"
private_key="${PKG_DIR_PATH}/files/privkey-ID.pem"
public_key="${PKG_DIR_PATH}/files/pubkey-Id.pem"
docker_file="${PKG_DIR_PATH}/Dockerfile"
docker_compose_file="${PKG_DIR_PATH}/docker-compose.yml"
docker_compose_overwrite="${PKG_DIR_PATH}/docker-compose.override.yml"
container_name=$(cut -d "-" -f3- <<< "${package_name}")
docker_exec_cmd="docker exec -it"
source "$CURDIR/utils"

argparse "$@"

function print_info() {
    echo "CURDIR = $CURDIR"
    echo "PKG_DIR_PATH = $PKG_DIR_PATH"
    echo "package_name = $package_name"
    echo "docker_file = $docker_file"
    echo "docker_compose_file = $docker_compose_file"
}

decrypted_data=$(decrypt_data $secret_file $private_key)
data_parser $decrypted_data

case "$ACTION" in
  start)
    echo "Starting continuous integration . . . "
    HOST="$HOST" \
    PORT="$PORT" \
    DEBUG="$DEBUG" \
    PACKAGE_NAME="$package_name"\
    docker compose -f $docker_compose_file -f $docker_compose_overwrite\
    up --remove-orphans --build -d
    ;;
  stop)
    echo "Stopping the container"
    HOST="$HOST" \
    PORT="$PORT" \
    DEBUG="$DEBUG" \
    PACKAGE_NAME="$package_name"\
    docker compose -f $docker_compose_file -f $docker_compose_overwrite\
    down --remove-orphans
    ;;
  connect)
    echo "Connecting the container $container_name - "
    ${docker_exec_cmd} ${container_name} /bin/bash
    ;;
  run)
    echo "Running  the container"
    ;;
  restart)
    echo "Restarting docker containers"
    docker compose restart
    ;;
  *)
    echo "Unknown arg..."
    ;;
esac
