#!/bin/bash
#set -ex

CURDIR=$(pwd)
PROJECT_HOME_PATH=$(cd "$CURDIR/../" && pwd)
config_file="${PROJECT_HOME_PATH}/src/config.py"
secret_file="${PROJECT_HOME_PATH}/.secrets"
private_key="$PROJECT_HOME_PATH/files/privkey-ID.pem"
public_key="$PROJECT_HOME_PATH/files/pubkey-Id.pem"
output_file="/tmp/ciphertext-ID.bin"


function encrypt_data(){
  local data_file=$1
  [ ! -f "$data_file" ] && echo "Secret file $data_file doesnt exist"; exit 1
  local output_file=${2:-$output_file}
  data=$(openssl pkeyutl -encrypt -pubin -in $data_file -inkey $public_key | base64 )
  echo $data > $output_file
}

function decrypt_data(){
  data_file=${1:-$output_file}
  [ ! -f "$data_file" ] && echo "Secret file $data_file doesnt exist"; exit 1
  local data_content=$(cat $data_file)
  echo $data_content | sed 's/\ /\n/g' | base64 --decode | openssl pkeyutl -decrypt -inkey $private_key
}

function cleanup() {
  files=${1:-$output_file}
  rm -rf $files
}
#encrypt_data $secret_file
decrypt_data
cleanup